[package]
name = "regit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["cargo"] }
console = "0.15.11"
dialoguer = "0.11.0"
indicatif = "0.17.11"
regex = "1.11.1"