[package]
name = "regit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["cargo"] }
console = "0.15.11"
futures = "0.3.31"
indicatif = "0.17.11"
regex = "1.11.1"
tokio = { version = "1", features = ["rt", "macros", "process", "fs"] }
